# Generated by Django 4.0.1 on 2022-01-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0002_song_song_chords'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='full_name',
            field=models.CharField(default='arijit', max_length=15),
            preserve_default=False,
        ),
    ]
